- name: Check 'name' variable
  assert:
    fail_msg: "'name' variable must be given"
    that:
    - name is defined

- name: Check 'path' variable
  assert:
    fail_msg: "'path' variable must be given"
    that:
    - path is defined

- name: Check destination directory (1)
  stat: path={{ path }}
  register: path_stats

- name: Check destination directory (2)
  assert:
    fail_msg: '{{ path }} must exist'
    that: path_stats.stat.exists | lower == 'true'

- name: Set facts
  set_fact:
    full_role_name: '{% if prefix != None %}{{ prefix }}-{% endif %}{{ name }}'
    clean_role_name: "{{ name | regex_replace('-', '_') | regex_replace('ansible_', '') }}"
    ansible_galaxy_options:
    - --offline
    - --init-path={{ path }}
#        - "--force" # Danger !!!

- name: Lancement d'ansible-galaxy
  command: ansible-galaxy init {{ ansible_galaxy_options | join(' ') }} {{ path }}/{{ full_role_name }}

- name: Création des fichiers de tâches et notifications
  template: src={{ item.src }}.yml.j2 dest={{ path }}/{{ full_role_name }}/{{ item.dest }}.yml
  with_items:
  - src: tasks/install
    dest: tasks/{{ clean_role_name }}_install
  - src: tasks/pre_install
    dest: tasks/{{ clean_role_name }}_pre_install
  - src: tasks/post_install
    dest: tasks/{{ clean_role_name }}_post_install
  - src: tasks/main
    dest: tasks/main
  - src: handlers/main
    dest: handlers/main
  - src: main.defaults
    dest: defaults/main

- name: Création des fichiers de variables par OS
  template: src=vars/{{ item }}.yml.j2 dest={{ path }}/{{ full_role_name }}/vars/{{ item }}.yml
  with_items:
  - debian
  - redhat

- name: Création du template de service consul
  copy: src=service.consul.json.j2 dest={{ path }}/{{ full_role_name }}/templates/service.consul.json.j2

- name: Création du README.md
  template: src=README.md.j2 dest={{ path }}/{{ full_role_name }}/README.md

- name: Création du Makefile
  template: src=Makefile.j2 dest={{ path }}/{{ full_role_name }}/Makefile

- name: Création du .gitignore
  copy: src=../.gitignore dest={{ path }}/{{ full_role_name }}

- name: Création du .pre-commit-config.yaml
  copy: src=../.pre-commit-config.yaml dest={{ path }}/{{ full_role_name }}

- name: Création du playbook de tests
  template: src=tests/main.yml.j2 dest={{ path }}/{{ full_role_name }}/tests/main.yml

- name: Création du fichier Vagrant
  template: src=Vagrantfile.j2 dest={{ path }}/{{ full_role_name }}/Vagrantfile

- name: Gestion des répertoires et fichiers
  file: path={{ path }}/{{ full_role_name }}/{{ item.name }} state={{ item.state }}
  with_items:
  - name: meta
    state: absent
  - name: tests/inventory
    state: absent
  - name: tests/test.yml
    state: absent
  - name: templates
    state: directory
  - name: vars/main.yml
    state: absent

