#
# {{ full_role_name }}
#

.PHONY: test # Testing YAML syntax and generating a test playbook
test:
	ansible-lint .

.PHONY: vagrant-destroy # Destroy Vagrant environment
vagrant-destroy:
	@vagrant destroy -f

.PHONY: vagrant-vbox # Test using Vagrant and Virtualbox
vagrant-vbox:
	@vagrant up --provider=virtualbox
	@vagrant provision

.PHONY: help # This help message
help:
	@grep '^.PHONY: .* #' Makefile \
		| sed 's/\.PHONY: \(.*\) # \(.*\)/\1\t\2/' \
		| expand -t20 \
		| sort
